language:
  python

python:
  - 3.5

env:
  fast_finish: true
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

install:
  - pip install --upgrade -r requirements.dev.txt

script:
  - python run.py review
  - python run.py test

after_success:
  - coveralls
